// global
export const ACTION_INIT_GLOBAL = 'ACTION_INIT_GLOBAL';
export const ACTION_UPDATE_GLOBAL = 'ACTION_UPDATE_GLOBAL';
export const ACTION_INIT_LOADING = 'ACTION_INIT_LOADING';
export const ACTION_UPDATE_LOADING = 'ACTION_UPDATE_LOADING';

// auth
export const ACTION_INIT_AUTH = 'ACTION_INIT_AUTH';
export const ACTION_UPDATE_AUTH = 'ACTION_UPDATE_AUTH';
