const tempDeals = [
  {
    id: `deal-0`,
    name: 'Lorem Ipsum',
    status: 'live',
    size: '100000',
    raisedAmount: '23500',
    model: 'ProRata',
    minimum: '250',
    maximum: '500',
    contribution: '310',
  },
  {
    id: `deal-1`,
    name: 'Lorem Ipsum',
    status: 'cancelled',
    size: '100000',
    raisedAmount: '23500',
    model: 'ProRata',
    minimum: '250',
    maximum: '500',
    contribution: '310',
  },
  {
    id: `deal-2`,
    name: 'Lorem Ipsum',
    status: 'paused',
    size: '100000',
    raisedAmount: '23500',
    model: 'ProRata',
    minimum: '250',
    maximum: '500',
    contribution: '310',
  },
  {
    id: `deal-3`,
    name: 'Lorem Ipsum',
    status: 'closed',
    size: '100000',
    raisedAmount: '23500',
    model: 'ProRata',
    minimum: '250',
    maximum: '500',
    contribution: '310',
  },
  {
    id: `deal-4`,
    name: 'Lorem Ipsum',
    status: 'closed',
    size: '100000',
    raisedAmount: '23500',
    model: 'ProRata',
    minimum: '250',
    maximum: '500',
    contribution: '310',
  },
];

export default tempDeals;
